"""Added fitness goal to users

Revision ID: 128dba0e812d
Revises: 72821c516a99
Create Date: 2026-03-06 07:08:54.647567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128dba0e812d'
down_revision = '72821c516a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitness_goal', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fitness_goal')

    # ### end Alembic commands ###
