"""Added gym classes and bookings

Revision ID: 72821c516a99
Revises: 768c07f8a5ef
Create Date: 2026-03-06 06:35:25.863760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72821c516a99'
down_revision = '768c07f8a5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('schedule_time', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['gym_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('gym_classes')
    # ### end Alembic commands ###
