"""Added capacity to classes

Revision ID: 838a03e92780
Revises: 128dba0e812d
Create Date: 2026-03-07 23:30:12.357797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838a03e92780'
down_revision = '128dba0e812d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_classes', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
